language: ruby
rvm:
  - '2.1.8'
  - '2.2.4'
  - '2.3.0'
gemfile:
  - gemfiles/activerecord_40.gemfile
  - gemfiles/activerecord_41.gemfile
  - gemfiles/activerecord_42.gemfile
env:
  - DB_USERNAME=postgres
services:
  - postgresql
before_script:
  - createdb activerecord_postgresql_plpgsql_test
