language: ruby
rvm:
  - '2.2.5'
  - '2.3.1'
gemfile:
  - gemfiles/activerecord_41.gemfile
  - gemfiles/activerecord_42.gemfile
  - gemfiles/activerecord_50.gemfile
env:
  - DB_USERNAME=postgres
services:
  - postgresql
before_script:
  - createdb activerecord_postgresql_plpgsql_test
addons:
  postgresql: '9.5'
