language: ruby
rvm:
  - '2.6.5'
  - '2.5.7'
gemfile:
  - gemfiles/activerecord_52.gemfile
  - gemfiles/activerecord_60.gemfile
env:
  - DB_USERNAME=postgres
services:
  - postgresql
before_script:
  - createdb activerecord_postgresql_plpgsql_test
addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
