language: ruby
rvm:
  - 2.6.5
  - 2.5.7
gemfile:
  - gemfiles/activerecord_52.gemfile
  - gemfiles/activerecord_60.gemfile
services:
  - docker
before_install:
  - docker-compose up -d
after_script:
  - docker-compose down
